####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/

homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
  - /config

####################################################
#                    Automation                    #
####################################################

# https://www.home-assistant.io/getting-started/automation/

automation: !include_dir_merge_list automations

####################################################
#                      Camera                      #
####################################################

# https://www.home-assistant.io/integrations/camera/

camera: !include_dir_merge_list camera

####################################################
#                       Cast                       #
####################################################

# https://cast.home-assistant.io/

cast: !include components/devices/cast.yaml

####################################################
#                 Device Tracker                   #
####################################################

# https://www.home-assistant.io/integrations/device_tracker/

device_tracker:
  - platform: netgear
    password: !secret netgear_password

####################################################
#                    Frontend                      #
####################################################

# https://www.home-assistant.io/integrations/frontend/

frontend:
  themes: !include_dir_named components/themes/

####################################################
#                  Geo Location                    #
####################################################

# https://www.home-assistant.io/integrations/geo_location/

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 3000
    minimum_magnitude: 0.0
    latitude: !secret latitude
    longitude: !secret longitude

####################################################
#                     Group                        #
####################################################

#  https://www.home-assistant.io/integrations/group/

group: !include_dir_merge_named components/group

####################################################
#                      HTTP                        #
####################################################

#https://home-assistant.io/components/http/

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

####################################################
#                 Input Boolean                    #
####################################################

#https://home-assistant.io/components/input_boolean/

input_boolean: !include_dir_merge_named components/input_boolean

####################################################
#                      YAML                        #
####################################################

#https://www.home-assistant.io/lovelace/yaml-mode/

lovelace:
  mode: yaml
  resources:
    [
    {'url':'/hacsfiles/Home-Assistant-Lovelace-HTML-Jinja2-Template-card/html-template-card.js', 'type':'module'},
    {'url':'/hacsfiles/lovelace-battery-entity/battery-entity.js', 'type':'module'},
    {'url':'/hacsfiles/button-card/button-card.js', 'type':'module'},
    {'url':'/hacsfiles/lovelace-card-mod/card-mod.js', 'type':'module'},
    {'url':'/hacsfiles/lovelace-card-tools/card-tools.js', 'type':'module'},
    {'url':'/hacsfiles/custom-header/custom-header.js', 'type':'module'},
    {'url':'/hacsfiles/jukebox.js', 'type': 'module'},
    {'url':'/hacsfiles/light-entity-card/light-entity-card.js', 'type':'module'},
    {'url':'/hacsfiles/lovelace-layout-card/layout-card.js', 'type':'module'},
    {'url':'/hacsfiles/lovelace-fold-entity-row/fold-entity-row.js', 'type':'module'},
    {'url':'/hacsfiles/mini-graph-card/mini-graph-card-bundle.js', 'type':'module'},
    {'url':'/hacsfiles/mini-media-player/mini-media-player-bundle.js', 'type':'module'},
    {'url':'/hacsfiles/search-card/search-card.js', 'type':'module'},
    {'url':'/hacsfiles/upcoming-media-card/upcoming-media-card.js', 'type':'module'},
    {'url':'/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js', 'type':'module'}
    ]

####################################################
#                      Script                      #
####################################################

# https://www.home-assistant.io/integrations/script/

script: !include_dir_merge_named components/script

####################################################
#                   Panel Custom                   #
####################################################

# https://www.home-assistant.io/integrations/panel_custom/

panel_custom: !include lovelace/panels/panel_custom.yaml

####################################################
#                     Recorder                     #
####################################################

# https://www.home-assistant.io/integrations/recorder/

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - group
      - input_boolean
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      - sensor.cpu_cores
      - sensor.current_scene
      - sensor.ipv4_address_eth0
      - sensor.tom_bilyeu
      - sensor.first_we_feast
      - sensor.version_friendly

####################################################
#                      Remote                      #
####################################################

# https://www.home-assistant.io/integrations/remote/

remote: !include components/devices/remote.yaml

####################################################
#                      Sensor                      #
####################################################

# https://www.home-assistant.io/integrations/sensor/

sensor: !include_dir_merge_list components/sensor

####################################################
#                  Shell Command                   #
####################################################

# https://www.home-assistant.io/integrations/shell_command/

shell_command: !include components/commands/shell_command.yaml

####################################################
#                      TTS                         #
####################################################

#https://www.home-assistant.io/integrations/google_translate/

tts:
  - platform: google_translate
    base_url: !secret base_url_tts

####################################################
#                   Weather                        #
####################################################

#https://www.home-assistant.io/components/weather.darksky/

weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api_key
