####################################################
#                Palm Beach Colors                 #
####################################################
# 137, 191, 255
# 56, 171, 255
# 255, 188, 232
# 255, 84, 84
####################################################
#                Scene Palm Beach                  #
####################################################

- alias: Palm Beach
  trigger:
    - platform: state
      entity_id: input_boolean.palm_beach_scene
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.scene_trigger

    - service: homeassistant.turn_off
      entity_id: input_boolean.default

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_1
        - light.livingroom_fan_bulb_2
      data:
       rgb_color: [137, 191, 255]
       brightness: 255

    - service: light.turn_on
      entity_id:
        - light.dining_room_bulb_1
        - light.livingroom_fan_bulb_1
      data:
        rgb_color: [56, 171, 255]
        brightness: 255

    - service: light.turn_on
      entity_id:
        - light.livingroom_light_strip
        - light.dining_room_bulb_2
      data:
        rgb_color: [255, 188, 232]
        brightness: 99

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_2
        - light.under_cabinet_light_strip
      data:
        rgb_color: [255, 84, 84]
        brightness: 99

    - service: switch.turn_off
      entity_id:
        - switch.kitchen_overhead_light
