####################################################
#                   Soho Colors                    #
####################################################
# rgb_color: 255,0,107
#
# rgb_color: 61,196,255
#
# rgb_color: 255,132,139
#
# rgb_color: 145,35,255
#
# rgb_color: 255,10,201

####################################################
#                   Scene Soho                     #
####################################################

- alias: Soho
  trigger:
    - platform: state
      entity_id: input_boolean.soho_scene
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.scene_trigger

    - service: homeassistant.turn_off
      entity_id: input_boolean.default

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_1
      data:
       rgb_color:
         - 255
         - 0
         - 107
       brightness: 200

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_2
      data:
       rgb_color:
         - 61
         - 196
         - 255
       brightness: 200

    - service: light.turn_on
      entity_id:
        - light.under_cabinet_light_strip
      data:
       rgb_color:
         - 255
         - 10
         - 201
       brightness: 200

    - service: light.turn_on
      entity_id:
        - light.dining_room_bulb_1
      data:
       rgb_color:
         - 255
         - 0
         - 107
       brightness: 200

    - service: light.turn_on
      entity_id:
        - light.dining_room_bulb_2
      data:
       rgb_color:
         - 61
         - 196
         - 255
       brightness: 200

    - service: light.turn_on
      entity_id:
        - light.livingroom_fan_bulb_1
      data:
       rgb_color:
         - 255
         - 132
         - 139
       brightness: 200

    - service: light.turn_on
      entity_id:
        - light.livingroom_fan_bulb_2
      data:
       rgb_color:
         - 145
         - 35
         - 255
       brightness: 200

    - service: light.turn_on
      entity_id:
        - light.livingroom_light_strip
      data:
       rgb_color:
         - 255
         - 10
         - 201
       brightness: 200
    - service: switch.turn_off
      entity_id:
        - switch.kitchen_overhead_light
