####################################################
#                  Tokyo Colors                    #
####################################################
# 198, 38, 255
# 33, 55, 255
# 221, 231, 255
# 255, 58, 129
####################################################
#                  Scene Tokyo                     #
####################################################

- alias: Tokyo
  trigger:
    - platform: state
      entity_id: input_boolean.tokyo_scene
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.scene_trigger

    - service: homeassistant.turn_off
      entity_id: input_boolean.default

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_1
        - light.livingroom_fan_bulb_2
      data:
       rgb_color: [198, 38, 255]
       brightness: 117

    - service: light.turn_on
      entity_id:
        - light.dining_room_bulb_1
        - light.livingroom_fan_bulb_1
      data:
        rgb_color: [33, 55, 255]
        brightness: 117

    - service: light.turn_on
      entity_id:
        - light.livingroom_light_strip
        - light.dining_room_bulb_2
      data:
        rgb_color: [221, 231, 255]
        brightness: 117

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_2
        - light.under_cabinet_light_strip
      data:
        rgb_color: [255, 58, 129]
        brightness: 117

    - service: switch.turn_off
      entity_id:
        - switch.kitchen_overhead_light
