####################################################
#            Tropical Twilight Colors              #
####################################################
# 255, 127, 10
# 255, 170, 109
# 236, 160, 255
# 189, 124, 255
####################################################
#            Scene Tropical Twilight               #
####################################################

- alias: Tropical Twilight
  trigger:
    - platform: state
      entity_id: input_boolean.tropical_twilight_scene
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.scene_trigger

    - service: homeassistant.turn_off
      entity_id: input_boolean.default

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_1
        - light.livingroom_fan_bulb_2
      data:
       rgb_color: [255, 127, 10]
       brightness: 255

    - service: light.turn_on
      entity_id:
        - light.kitchen_bar_light_2
        - light.livingroom_fan_bulb_1
      data:
        rgb_color: [255, 170, 109]
        brightness: 255

    - service: light.turn_on
      entity_id:
        - light.livingroom_light_strip
        - light.dining_room_bulb_2
      data:
        rgb_color: [236, 160, 255]
        brightness: 255

    - service: light.turn_on
      entity_id:
        - light.dining_room_bulb_1
        - light.under_cabinet_light_strip
      data:
        rgb_color: [189, 124, 255]
        brightness: 255

    - service: switch.turn_off
      entity_id:
        - switch.kitchen_overhead_light
