- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret server_ip
  port: 8989
  days: 7
  ssl: false
  max: 10
- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: !secret server_ip
  port: 7878
  days: 120
  ssl: false
  theaters: true
  max: 10
