- platform: youtube
  channel_id: UCPD_bxCRGpmmeQcbe2kpPaA
- platform: youtube
  channel_id: UCnYMOamNKLGVlJgRUbamveA
- platform: youtube
  channel_id: UCFNTq9XKHDNy_1-2lL0kqCg
- platform: youtube
  channel_id: UCZDfnUn74N0WeAPvMqTOrtA
